apiVersion: v1
kind: Service
metadata:
  name: lb-app
spec:
  type: LoadBalancer
  selector:
    app: app-api-persona
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: listener-1