apiVersion: v1
kind: Pod
metadata:
  name: db-k8s-api-persona
  annotations:
    sample: 800-555-1212
  labels:
    app: db-k8s-api-persona
    version: v1
spec:
  containers:
   - name: db
     image: dalvarez07/db_k8s:1.0.0
     ports:
        - containerPort: 3306