apiVersion: v1
kind: Service
metadata:
  name: db-k8s-api
spec:
  type: ClusterIP
  selector:
    app: db-k8s-api-persona
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306 # puertos que usan los pods