apiVersion: v1
kind: Service
metadata:
  name: app-k8s-api
spec:
  type: ClusterIP
  selector:
    app: app-k8s-api-persona
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 # puertos que usan los pods